# Logstash主配置文件
http.host: "0.0.0.0"
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

# 管道配置
path.config: /usr/share/logstash/pipeline
config.reload.automatic: true
config.reload.interval: 3s

# 性能配置
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# 日志配置
log.level: info
path.logs: /var/log/logstash